### ISSUE TITLE
Vagrant OS X pkg: symlinks in /usr/bin will not be supported on El Capitan

### ISSUE THREAD

**Issue by timsutton** [mitchellh/vagrant-installers#54]
On OS X 10.11, installing the vagrant pkg will result in success, however a new security feature of OS X prevents user modification to certain system folders, including `/usr/bin` (it can be overridden, but non-trivially). A snippet from the install log where a symlink attempts to be created in `/usr/bin`:

```
Jun  9 12:48:37 test-mini installd[375]: ./postinstall: ln: /usr/bin/vagrant: Operation not permitted
```

Tools and Puppet and Chef have similar issues, for example:

https://tickets.puppetlabs.com/browse/PUP-4714

`/usr/local/bin` is in the default `PATH` so it seems natural that the vagrant symlink could go there. Alternatively there's also the option of dropping additional paths in `/etc/paths.d`, but I'm not sure which shells beyond the stock Bash will automatically include those.

**Comment by BrianGilbert** [comment]
The following allowed me to get vagrant up and running on 10.11, not sure if it's the best dir to use.. but it works:
```
cd /usr/local/bin
ln -s /opt/vagrant/bin/vagrant vagrant
```

**Comment by mitchellh** [comment]
Fixed, will be in 1.7.3. Moving to /usr/local for now.

**Comment by jelyman2** [comment]
FWIW, this is still an issue in 1.7.4 on 10.11. Brian's solution worked for me.

**Comment by mbeijen** [comment]
Unboxed brand new MacBook today; hoped to be productive very soon thanks to Vagrant but ran into this issue, unfortunately.

**Comment by timsutton** [comment]
What was the exact issue? Did the pkg installer fail?

Does `/usr/local/bin` actually _exist_ on a brand new out-of-the-box 10.11 system? I noticed this issue in the install script, and now see it was resolved in https://github.com/mitchellh/vagrant-installers/pull/62, but that change is not yet in a released pkg.

**Comment by mbeijen** [comment]
Thanks for the fast reply! The installer did not fail, just as this issue states, it fails 'silently', but `vagrant` is not in path after installation. I see how #62 indeed creates /usr/local/bin and would fix the issue.

**Comment by timsutton** [comment]
Yeah. Most people get `/usr/local/bin` on their system if Homebrew is something they use and set up early. It's in the default `PATH`, but not necessarily created unless by something like an installer pkg. Since 10.11 and SIP, probably many more installer packages will be putting things here though.

**Comment by mbeijen** [comment]
For me, vagrant was the very first thing I installed. If I'd installed vagrant via Homebrew, things might have been fine...

**Comment by timsutton** [comment]
"that change is not yet in a released pkg" <-- guess it is [now](https://t.co/cCBuE0rVqD)
